services:
  app-test-drom-2:
    image: php:8.2-fpm
    container_name: app-test-drom-2
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      XDEBUG_MODE: debug
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile